name: pyLAP
channels:
  - huggingface
  - pytorch
  - plotly
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.7
  - anaconda
  - dill
  - glob2
  - spacy
  - scikit-image
  - plotly
  - ipywidgets
  - ipykernel
  - ipyparallel
  - ipython
  - ipython_genutils
  - ipywidgets
  - tensorflow
  - tensorboard
  - nb_conda
  - pymongo
  - line_profiler
  - memory_profiler
  - ipyparallel
  - plotnine
  - pyopengl
  - torchvision
  - torchaudio
  - pytorch
  - torchtext
  - transformers
  - wandb
  - natsort
