name: pyLAP
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7.10
  - pytorch=1.8.1
  - torchaudio=0.8.1
  - torchvision=0.9.1
  - pip:
    - bertviz==1.0.0
    - folium==0.2.1
    - jupyterlab==3.0.14
    - notebook==6.3.0
    - transformers==4.5.0
    - urllib3==1.25.4
    - wandb==0.10.25
